version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8010:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  backend:
    image: papila1011/dockernodejsapp:latest
    expose:
      - "8080"